name: fstore
publish_to: "none"
description: Mobile commerce app by Flutter

# Release version: v3.13.0 (Do not change this line)
version: 6.1.7+74

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  inspireui: ^2.2.7

  flux_firebase:
    path: packages/flux_firebase/

  # Base
  flutter_localization: ^0.3.0
  intl: ^0.19.0
  crypto: 3.0.6
  path_provider: 2.1.5
  url_launcher: 6.3.1
  flutter_secure_storage: 9.2.4
  hive: 2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  dio: ^5.7.0
  http_auth: ^1.0.4
  share: 2.0.4
  tuple: 2.0.2
  collection: ^1.19.0
  quiver: 3.2.1
  async: 2.12.0
  html: 0.15.5
  vector_math: 2.1.4
  path: ^1.9.0
  flutter_svg: 2.0.17
  notification_permissions: 0.6.1
  flutter_local_notifications: 19.0.0
  onesignal_flutter: ^5.2.9
  new_version_plus: ^0.0.10

  # STATE MANAGEMENT
  provider: 6.1.2
  get_it: ^8.0.3

  # SPLASH SCREEN, ONBOARD
  lottie: 3.3.1
  rive: ^0.13.20

  # WEB TOOLS
  html_unescape: 2.0.0
  webview_flutter: 4.7.0
  webview_flutter_web: 0.2.3+4
  flutter_inappwebview: 6.0.0
  responsive_builder: ^0.7.1

  # HTML render
  flutter_widget_from_html_core: 0.15.2
  fwfh_svg: 0.8.3
  fwfh_cached_network_image: 0.14.3
  fwfh_url_launcher: 0.9.1
  #  fwfh_chewie: 0.7.1+2 # accentColor issue
  fwfh_webview: ^0.15.3
  fwfh_text_style: 2.23.8

  # VIDEO
  video_player: 2.9.2
  youtube_player_iframe: 5.1.0
  # MAP
  google_maps_flutter: 2.10.0
  geocode: 1.0.3
  location: 7.0.1

  # AUTHENTICATION
  local_auth: 2.3.0
  the_apple_sign_in: 1.1.1
  flutter_facebook_auth: ^7.1.1
  google_sign_in: 6.2.2
  sms_autofill: ^2.4.1
  permission_handler: ^11.3.1

  # FILES, IMAGES
  file_picker: 10.0.0
  cached_network_image: 3.4.1
  image: 4.5.4
  transparent_image: 2.0.1
  image_picker: 1.1.2
  flutter_native_image: 0.0.6+1
  flutter_cache_manager: 3.4.1
  wechat_assets_picker: ^9.4.2
  photo_manager: ^3.6.3

  # TOOLS
  google_fonts: ^6.2.1
  random_string: 2.3.1
  json_annotation: 4.9.0
  freezed_annotation: 2.4.4
  timeago: 3.7.0 # depend on intl
  universal_platform: 1.1.0
  uuid: ^4.5.1
  easy_debounce: 2.0.3
  devicelocale: ^0.8.1
  visibility_detector: ^0.4.0+2 # depend on google ads
  rate_my_app: 2.2.0
  flutter_linkify: ^6.0.0
  gms_check: 1.0.3
#  google_mobile_ads: 5.3.1
  speech_to_text: 7.0.0
  flutter_keyboard_visibility: ^6.0.0

  # UI
  flutter_spinkit: ^5.2.1
  smooth_page_indicator: ^1.2.0+3
  animated_text_kit: 4.2.2
  flash: ^3.1.1
  flutter_staggered_grid_view: 0.7.0
  pin_code_fields: 8.0.1
  country_pickers: ^3.0.1
  dropdown_search: ^6.0.2
  intro_slider: 4.2.1
  extended_image: ^9.1.0
  dotted_decoration: 2.0.0
  awesome_card: 1.1.7
  qr_code_scanner: 1.0.1
  flutter_calendar_carousel: 2.5.3 # use intl 0.18.0
  sticky_headers: 0.3.0+2
  archive: ^4.0.5
  jumping_dot: 0.0.7
  fl_chart: 0.70.0
  tiktoklikescroller: 0.2.8
  readmore: ^3.0.0
  flutter_animate: ^4.5.2
  flutter_async_autocomplete: 0.1.1
  scrollable_positioned_list: 0.3.8
  country_code_picker: 3.1.0
  carousel_slider: ^5.0.0
  rect_getter: ^1.1.0
  scroll_to_index: ^3.0.1
  flutter_zoom_drawer: ^3.2.0
  infinite_carousel: ^1.1.1

  ### Native Payment
  razorpay_flutter:
    git:
      url: https://github.com/inspireui/razorpay-flutter
      ref: 2daadbaa4d56c1ded1c79cc7e763efc929812252
  paytm_allinonesdk: ^1.2.8
  pay_with_paystack: ^1.0.11


  flutter_paystack:
    git:
      url: https://github.com/inspireui/flutter_paystack
      ref: a2f084e96998135ba2f05165887d0750f79852c8
#  flutterwave_standard: ^1.0.8


  #### For Shopify GraphQL
  graphql: ^5.1.2

  ### Flutter 3 fix warning
  intl_phone_number_input: 0.7.4 # custom feature for phone number
#    git:
#      url: https://github.com/inspireui/intl_phone_number_input
#      ref: d0d359cfabaf3dbefba762cb4d9db3f66ea83f4a
  flutter_swiper_null_safety:
    git:
      url: https://github.com/inspireui/flutter_swiper_null_safety
      ref: 18e8d2d642ff9e0013fc4477c6d64c52732b463a
  flare_flutter:
    git:
      url: https://github.com/inspireui/Flare-Flutter.git
      ref: fd4bcba22aae4c028286e453deeb78f3311e689a
      path: flare_flutter
  pull_to_refresh:
    git:
      url: https://github.com/inspireui/flutter_pulltorefresh
      ref: 6d7fbdd5b3cde242a474d66da312aac4aa892b9b
  multiple_localization:
    git:
      url: https://github.com/inspireui/flutter_multiple_localization
      ref: 48b65fa88ed468331d56ee86a102d808596c0a50

  ###---- Some extra feature is disable by default -----###
  ### ðŸ’³ Facebook Ads
  ### Search "Enable Facebook Ads" & uncomment to use  - https://tppr.me/9Pkf9
  # facebook_audience_network: 1.0.1

  ### â¬‡ï¸ Enable In App Update on Android feature
  ### Uncomment file lib/common/tools/in_app_update_for_android.dart
  in_app_update: ^4.2.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: 2.0.2
  flutter_native_splash: 2.3.2
  build_runner: ^2.4.15
  freezed: ^3.0.0-0.0.dev
  json_serializable: ^6.9.4

dependency_overrides:
  # inspireui: 1.6.0
  async: ^2.11.0


### Enable to use Flutter Test Driver
#  flutter_driver:
#    sdk: flutter
#  test: 1.16.5
#  dependency_validator: 3.2.2  # pub run dependency_validator

### Enable Generate Icon library
#  flutter_launcher_icons:
#    git:
#      url: https://github.com/inspireui/flutter_launcher_icons.git
#      ref: 7aab578231120ef39d37db34e07dce3c7995ee14

#  Run this script to generate the app icon: flutter pub run flutter_launcher_icons:main

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/config/
    - lib/config/states/
    - lib/config/stories/
    - lib/config/us_store/
    - lib/config/vi_store/
    - assets/icons/brands/
    - assets/icons/credit_cards/
    - assets/icons/tabs/
    - assets/icons/payment/
    - assets/icons/logins/
    - assets/images/
    - assets/images/country/
    - assets/images/favicon/
    - assets/map_styles/
    - assets/html/
    - google_fonts/

flutter_intl:
  enabled: true
  use_deferred_loading: true